services:
  bot:
    build:
      context: app
      dockerfile: Dockerfile

    env_file: .env

    networks:
      - kuska_network

    user: bot

    stop_signal: SIGINT

    depends_on:
      - database
      - redis

    restart: always

    entrypoint: [ ".venv/bin/python", "-m", "bot" ]


  database:
    image: postgres:16.3
    shm_size: 1gb

    environment:
      - POSTGRES_USER=$PSQL_USER
      - POSTGRES_PASSWORD=$PSQL_PASSWORD
      - POSTGRES_DB=$PSQL_DB

    networks:
      - kuska_network

    ports:
      - "5432:5432"

    volumes:
      - ./psql/data:/var/lib/postgresql/data
      - ./psql/db-init-scripts:/docker-entrypoint-initdb.d


    restart: always

  redis:
    image: redis:7.2.5

    command:
      - --port 6379
      - --protected-mode no
      - --loglevel notice
      - --requirepass $REDIS_PASSWORD
      - --maxmemory 256MB
      - --save 60 10
      - --dir /data
      - --dbfilename dump.rdb
      - --rdbcompression yes
      - --rdbchecksum yes
      - --always-show-logo yes

    networks:
      - kuska_network

    ports:
      - "6379:6379"

    volumes:
      - ./redis/data:/data

    restart: always

    entrypoint: [ "redis-server" ]

networks:
  kuska_network:
